[shell]
program = "/opt/homebrew/bin/fish"
args = ["-i"]

# Window
[window]
padding = { x = 14, y = 14 }
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
option_as_alt = "Both"

# Font
[font]
normal = { family = "Monaspace Neon", style = "Regular" }
bold = { family = "Monaspace Neon", style = "Bold" }
italic = { family = "Monaspace Neon", style = "Italic" }
bold_italic = { family = "Monaspace Neon", style = "Bold Italic" }
size = 15.0
offset = { x = 0, y = 28 }
glyph_offset = { x = 0, y = 14 }

# Colors
[colors]
footer_bar = { foreground = "#F0F0F5", background = "#24232E" }
selection = { foreground = "#F0F0F5", background = "#5D5D75" }

[colors.primary]
foreground = "#F0F0F5"
background = "#24232E"

[colors.search]
matches = { foreground = "#24232E", background = "#686f92" }
focused_match = { foreground = "#24232E", background = "#9eb4eb" }

[colors.normal]
black = "#353243"
red = "#f67e90"
green = "#b2f5bf"
yellow = "#f4c58a"
blue = "#9FB5EB"
magenta = "#ECA2D8"
cyan = "#87FEEB"
white = "#E7E6F0" # light-gray

[colors.bright]
black = "#504c67" # gray
red = "#fab7c1"
green = "#e8fcec"
yellow = "#f9e1c2"
blue = "#d0dbf5"
magenta = "#f6d5ed"
cyan = "#c2fef4"
white = "#ffffff" #white

[colors.dim]
black = "#353243"
red = "#935869"
green = "#718e7f"
yellow = "#8f7666"
blue = "#686f92"
magenta = "#8d688b"
cyan = "#5f9191"
white = "#8a8896"

[keyboard]
bindings = [
{ key = "[", mods = "Command", action = "SelectPreviousTab" },
{ key = "]", mods = "Command", action = "SelectNextTab" },
{ key = "n", mods = "Super", action = "SpawnNewInstance" },
]
