[shell]
program = "/opt/homebrew/bin/fish"
args = ["-i"]

# Window
[window]
padding = { x = 14, y = 14 }
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
option_as_alt = "Both"

# Font
[font]
normal = { family = "Monaspace Neon", style = "Regular" }
bold = { family = "Monaspace Neon", style = "Bold" }
italic = { family = "Monaspace Neon", style = "Italic" }
bold_italic = { family = "Monaspace Neon", style = "Bold Italic" }
size = 15.0
offset = { x = 0, y = 28 }
glyph_offset = { x = 0, y = 14 }

# Colors
[colors]
footer_bar = { foreground = "#F1F0FF", background = "#222232" }
selection = { foreground = "#F1F0FF", background = "#6981A4" }

[colors.primary]
foreground = "#F1F0FF"
background = "#21202C"

[colors.search]
matches = { foreground = "#F1F0FF", background = "#57535F" }
focused_match = { foreground = "#222232", background = "#9FC1EB" }

[colors.bright]
black = "#4D4B68" # gray
red = "#F67C8E"
green = "#B1F5BE"
yellow = "#F4CA8B"
blue = "#9FC1EB"
magenta = "#ECA2D8"
cyan = "#87F1FE"
white = "#E3E3E8" #white

# test
[colors.normal]
black = "#21202C"
red = "#C95368"
green = "#7CC08F"
yellow = "#F1BF74"
blue = "#80A1CA"
magenta = "#CA83B7"
cyan = "#64D1D7"
white = "#ABAABB" # light-gray

[colors.dim]
black = "#21202C"
red = "#753A4A"
green = "#4F705E"
yellow = "#897050"
blue = "#51617B"
magenta = "#765272"
cyan = "#437981"
white = "#666574"

[keyboard]
bindings = [
{ key = "[", mods = "Command", action = "SelectPreviousTab" },
{ key = "]", mods = "Command", action = "SelectNextTab" },
{ key = "n", mods = "Super", action = "SpawnNewInstance" },
]
