[shell]
program = "/opt/homebrew/bin/fish"
args = ["-i"]

# Window
[window]
padding = { x = 14, y = 14 }
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
option_as_alt = "Both"

# Font
[font]
normal = { family = "Monaspace Neon", style = "Regular" }
bold = { family = "Monaspace Neon", style = "Bold" }
italic = { family = "Monaspace Neon", style = "Italic" }
bold_italic = { family = "Monaspace Neon", style = "Bold Italic" }
size = 15.0
offset = { x = 0, y = 28 }
glyph_offset = { x = 0, y = 14 }

# Colors
[colors]
footer_bar = { foreground = "#ebeaf2", background = "#242232" }
selection = { foreground = "#ebeaf2", background = "#a7bdf2" }

[colors.primary]
foreground = "#ebeaf2"
# oklch(26% 0.03 290)
background = "#242232"

[colors.search]
matches = { foreground = "#242232", background = "#626a8c" }
focused_match = { foreground = "#242232", background = "#a7bdf2" }

[colors.normal]
black = "#2d2b3c"
red = "#ff9cb4"
green = "#8ed09c"
yellow = "#d7ba82"
blue = "#a7bdf2"
magenta = "#eba2d8"
cyan = "#60d5c2"
white = "#ebeaf2" # light-gray

[colors.bright]
black = "#4c4966" # gray
red = "#ffe3ea"
green = "#c0e5c8"
yellow = "#e8d8b8"
blue = "#e5ecfb"
magenta = "#f8ddf1"
cyan = "#98e4d8"
white = "#ffffff" #white

[colors.dim]
black = "#282637"
red = "#8b5c70"
green = "#587365"
yellow = "#79695a"
blue = "#626a8c"
magenta = "#815e80"
cyan = "#467676"
white = "#807e8c"

[keyboard]
bindings = [
{ key = "[", mods = "Command", action = "SelectPreviousTab" },
{ key = "]", mods = "Command", action = "SelectNextTab" },
{ key = "n", mods = "Super", action = "SpawnNewInstance" },
]
