[shell]
program = "/opt/homebrew/bin/fish"
args = ["-i"]

# Window
[window]
padding = { x = 14, y = 14 }
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
option_as_alt = "Both"

# Font
[font]
normal = { family = "Monaspace Neon", style = "Regular" }
bold = { family = "Monaspace Neon", style = "Bold" }
italic = { family = "Monaspace Neon", style = "Italic" }
bold_italic = { family = "Monaspace Neon", style = "Bold Italic" }
size = 15.0
offset = { x = 0, y = 28 }
glyph_offset = { x = 0, y = 14 }

# Colors
[colors]
footer_bar = { foreground = "#F0F0F5", background = "#24232E" }
selection = { foreground = "#F0F0F5", background = "#5D5D75" }

[colors.primary]
foreground = "#F0F0F5"
background = "#24232E"

[colors.search]
matches = { foreground = "#24232E", background = "#5D5D75" }
focused_match = { foreground = "#24232E", background = "#B7C1EB" }

[colors.bright]
black = "#5D5D75" # gray
red = "#F593A2"
green = "#C9F5D1"
yellow = "#F5D4A4"
blue = "#B7C1EB"
magenta = "#EDBBED"
cyan = "#A1FFEF"
white = "#F0F0F5" #white

[colors.normal]
black = "#343242"
red = "#F67C8E"
green = "#B1F5BE"
yellow = "#F4CA8B"
blue = "#9FB5EB"
magenta = "#ECA2D8"
cyan = "#87FEEB"
white = "#E7E6F0" # light-gray

[colors.dim]
black = "#5D5D75"
red = "#F593A2"
green = "#C9F5D1"
yellow = "#F5D4A4"
blue = "#B7C1EB"
magenta = "#EDBBED"
cyan = "#A1FFEF"
white = "#F0F0F5"

[keyboard]
bindings = [
{ key = "[", mods = "Command", action = "SelectPreviousTab" },
{ key = "]", mods = "Command", action = "SelectNextTab" },
{ key = "n", mods = "Super", action = "SpawnNewInstance" },
]
