[shell]
program = "/opt/homebrew/bin/fish"
args = ["-i"]

# Window
[window]
padding = { x = 14, y = 14 }
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
option_as_alt = "Both"

# Font
[font]
normal = { family = "Monaspace Neon", style = "Regular" }
bold = { family = "Monaspace Neon", style = "Bold" }
italic = { family = "Monaspace Neon", style = "Italic" }
bold_italic = { family = "Monaspace Neon", style = "Bold Italic" }
size = 15.0
offset = { x = 0, y = 28 }
glyph_offset = { x = 0, y = 14 }

# Colors
[colors]
footer_bar = { foreground = "#edecf4", background = "#24232E" }
selection = { foreground = "#edecf4", background = "#4a4c64" }

[colors.primary]
foreground = "#edecf4"
background = "#24232E"

[colors.search]
matches = { foreground = "#24232E", background = "#4a4c64" }
focused_match = { foreground = "#24232E", background = "#9eb4eb" }

[colors.normal]
black = "#312e3d"
red = "#f67e90"
green = "#b2f5bf"
yellow = "#f4c58a"
blue = "#9FB5EB"
magenta = "#ECA2D8"
cyan = "#86feea"
white = "#edecf4" # light-gray

[colors.bright]
black = "#534f69" # gray
red = "#fbc6ce"
green = "#f6fef7"
yellow = "#fbe8d0"
blue = "#dde5f8"
magenta = "#f9e1f3"
cyan = "#d2fff7"
white = "#ffffff" #white

[colors.dim]
black = "#282531"
red = "#563946"
green = "#465351"
yellow = "#544745"
blue = "#404359"
magenta = "#514054"
cyan = "#3f545a"
white = "#504e5a"

[keyboard]
bindings = [
{ key = "[", mods = "Command", action = "SelectPreviousTab" },
{ key = "]", mods = "Command", action = "SelectNextTab" },
{ key = "n", mods = "Super", action = "SpawnNewInstance" },
]
