# use this to swap between themes
# sed -i -e 's/theme-dark/theme-light/g' ~/.dotfiles/alacritty/alacritty.yml
# sed -i -e 's/theme-light/theme-dark/g' ~/.dotfiles/alacritty/alacritty.yml
[general]
import = ["~/.dotfiles/alacritty/theme-dark.toml"]

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["-i"]

# Window
[window]
padding = { x = 12, y = 12 }
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
option_as_alt = "OnlyLeft"

# Font
[font]
normal = { family = "MonaspiceNe NFM", style = "Regular" }
bold = { family = "MonaspiceNe NFM", style = "Bold" }
italic = { family = "MonaspiceNe NFM", style = "Italic" }
bold_italic = { family = "MonaspiceNe NFM", style = "Bold Italic" }
size = 15.0
offset = { x = 0, y = 24 }
glyph_offset = { x = 0, y = 12 }


[keyboard]
bindings = [
{ key = "[", mods = "Command", action = "SelectPreviousTab" },
{ key = "]", mods = "Command", action = "SelectNextTab" },
{ key = "n", mods = "Super", action = "SpawnNewInstance" },
]


[terminal]
