# https://huetone.ardov.me/?palette=N4IgdghgtgpiBcIDiBLALgCQK4CMAEAFAAoBOKsJAlHgMYD2ADgJ4gA0IAFljAM4IDaoSLAQgAQgBsINANZsQ9CXRJ94-EAGIAzDh0AWACbyNAJgAc5rQE5jABhq2cARgggAugF9WQ6HEQAlGCN2RWVVdQ0AMxoaLRpXdiiYCCccOESANhg9CD1I9y8fEUQkEhgYMHlQlQFNMxoYGhwM4wB2MwMzCC1jLQMAVmycAu9wX1EATRgJJQB3KrolGrVNGGjklsSDHB2rHsycPJNXT1HhP3EJbgWl8M0aEwM84M0IaVtIzc09K37%2B1pMIyKFwAshAAOYVNAJBSLMK1DQGAw0KyRdL3bYfF4afq5T5GU7A0QAYSYEEqIThywi7UanWMGT69X6vS0-Ui-yBY2KIAA6hx0OjqncomZIq1IvlEjBWjLysY-v09P1hp43Ow0HQwLxajgyOCOGh5GBlFAIBJ5AZyAUgA
# https://huetone.ardov.me
# {
#   "name": "Gatito Theme (dark)",
#   "hues": [
#     {
#       "name": "Black",
#       "colors": [
#         "#3b3b4d",
#         "#282839",
#         "#0c0b1a"
#       ]
#     },
#     {
#       "name": "Red",
#       "colors": [
#         "#fcc3ca",
#         "#fea1be",
#         "#6e4a4f"
#       ]
#     },
#     {
#       "name": "Green",
#       "colors": [
#         "#8cecb6",
#         "#78d8a3",
#         "#3d5e4b"
#       ]
#     },
#     {
#       "name": "Yellow",
#       "colors": [
#         "#efcea6",
#         "#dbbb93",
#         "#6b4f2a"
#       ]
#     },
#     {
#       "name": "Blue",
#       "colors": [
#         "#c2d4fd",
#         "#aac0f6",
#         "#495572"
#       ]
#     },
#     {
#       "name": "Magenta",
#       "colors": [
#         "#ddc9fe",
#         "#cdb0fd",
#         "#5a4f6d"
#       ]
#     },
#     {
#       "name": "Cyan",
#       "colors": [
#         "#78ecd8",
#         "#63d8c5",
#         "#335f57"
#       ]
#     },
#     {
#       "name": "White",
#       "colors": [
#         "#f8f7ff",
#         "#e7e7ee",
#         "#55545b"
#       ]
#     }
#   ],
#   "tones": [
#     "bright",
#     "normal",
#     "dim"
#   ]
# }

# Colors
[colors]
# white, background
footer_bar = { foreground = "#282839", background = "#e7e7f2" }
# white, blue
selection = { foreground = "#282839", background = "#e7e7ee" }

[colors.primary]
# white
foreground = "#282839"
background = "#e7e7f2"

[colors.search]
# background, blue dim
matches = { foreground = "#e3e2ea", background = "#7e8cab" }
# background, blue
focused_match = { foreground = "#e3e2ea", background = "#31416f" }

[colors.bright]
black = "#eeedf5" # gray
red = "#542830"
green = "#074329"
yellow = "#4c320b"
blue = "#293757"
magenta = "#3f2d58"
cyan = "#144039"
white = "#3b3b4d" #white

[colors.normal]
black = "#e7e7f2"
red = "#712241"
green = "#185034"
yellow = "#593e18"
blue = "#31416f"
magenta = "#4f3274"
cyan = "#214c45"
white = "#282839" # light-gray


[colors.dim]
black = "#e3e2ea"
red = "#a88085"
green = "#649a7b"
yellow = "#a58660"
blue = "#7e8cab"
magenta = "#9185a6"
cyan = "#6a978e"
white = "#0c0b1a"

