# https://huetone.ardov.me/?palette=N4IgdghgtgpiBcIDiEAuBLVB7ABAFQAsZYcAKAEwgCcBrAShABoQCBXGAZwQG1RJYEIAEIAbCAGMaTEOKwisVLvG4gAxAGYARloAs5aaoBMAdhPrjIALoBfRn2hxEAJRj7ms%2BYp5qAZj-EAjOIAnAY%2BMBABmnA2duAOgkhUMDBg0h4KSiqqABziMOKaAGwGxjnkORDqVrb2AogAmjAi8gDu6XKZ3qow-hElzKrkmiPB1bF1jsIi7B2eWWrihuQ6Pm5qEBIADD4lE-H1IACyEADmqagQc13KauTkIeEG4sM7%2Bvv8UwDCAJ4Qae5Ol5bqoygUKgYiuoKuIAKw1OKfQQAdQImDggPm3R8OR8xj8z3U4iJVxslmY2DAnG8mio6FOBFQ0jACigEBENSAA# Colors

[colors]
# white, background
footer_bar = { foreground = "#dbdce3", background = "#1f2030" }
# black, blue
selection = { foreground = "#262738", background = "#a5b7e2" }

[colors.primary]
# white
foreground = "#dbdce3"
background = "#1f2030"

[colors.search]
# background, blue dim
matches = { foreground = "#1f2030", background = "#464d62" }
# background, blue
focused_match = { foreground = "#1f2030", background = "#a5b7e2" }

[colors.normal]
black = "#262738"
red = "#e3a4aa"
green = "#72ce9b"
yellow = "#d2b18a"
blue = "#a5b7e2"
magenta = "#bfade0"
cyan = "#58cebb"
white = "#dbdce3" # light-gray

[colors.bright]
black = "#3a3c4d" # gray
red = "#febdc3"
green = "#8ce8b4"
yellow = "#eccba2"
blue = "#bed1fd"
magenta = "#d9c6fb"
cyan = "#75e9d5"
white = "#f5f6fe" #white

[colors.dim]
black = "#202131"
red = "#5c464f"
green = "#35554b"
yellow = "#564b45"
blue = "#464d62"
magenta = "#4f4962"
cyan = "#2c5555"
white = "#595a62"

