# https://huetone.ardov.me/?palette=N4IgdghgtgpiBcIDiEAuBLVB7ABAFQAsZYcAKAEwgCcBrAShABoQCBXGAZwQG1RJYEIAEIAbCAGMaTEOKwisVLvG4gAxAGYARloAs5aaoBMAdhPrjIALoBfRn2hxEAJRj7ms%2BYp5qAZj-EAjOIAnAY%2BMBABmnA2duAOgkhUMDBg0h4KSiqqABziMOKaAGwGxjnkORDqVrb2AogAmjAi8gDu6XKZ3qow-hElzKrkmiPB1bF1jsIi7B2eWWrihuQ6Pm5qEBIADD4lE-H1IACyEADmqagQc13KauTkIeEG4sM7%2Bvv8UwDCAJ4Qae5Ol5bqoygUKgYiuoKuIAKw1OKfQQAdQImDggPm3R8OR8xj8z3U4iJVxslmY2DAnG8mio6FOBFQ0jACigEBENSAA# Colors

[colors]
# white, background
footer_bar = { foreground = "#bfc0c7", background = "#1f2030" }
# white, blue
selection = { foreground = "#262738", background = "#aac0f6" }

[colors.primary]
# white
foreground = "#bfc0c7"
background = "#1f2030"

[colors.search]
# background, blue dim
matches = { foreground = "#1f2030", background = "#3d415a" }
# background, blue
focused_match = { foreground = "#1f2030", background = "#aac0f6" }

[colors.normal]
black = "#262738"
red = "#fea1be"
green = "#7cd8a4"
yellow = "#dcbb93"
blue = "#aac0f6"
magenta = "#cdb0fd"
cyan = "#63d8c5"
white = "#bfc0c7" # light-gray

[colors.bright]
black = "#3a3c4d" # gray
red = "#ffb4d1"
green = "#90ebb7"
yellow = "#efcea6"
blue = "#bdd3ff"
magenta = "#e0c4ff"
cyan = "#78ecd8"
white = "#d3d4db" #white

[colors.dim]
black = "#202131"
red = "#664556"
green = "#38594e"
yellow = "#5a4e48"
blue = "#485069"
magenta = "#544a6c"
cyan = "#305958"
white = "#4f5059"

