code --install-extension ban.spellright
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension karigari.chat
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension pawelgrzybek.gatito-theme
