pnpm add -g @astrojs/language-server
pnpm add -g @biomejs/biome
pnpm add -g @tailwindcss/language-server 
pnpm add -g avif
pnpm add -g aws-cdk
pnpm add -g emmet-ls
pnpm add -g imageoptim-cli
pnpm add -g prettier
pnpm add -g typescript
pnpm add -g typescript-language-server
pnpm add -g vscode-langservers-extracted
