[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.emmet-ls]
args = ["--stdio"]
command="emmet-ls"

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "./node_modules/typescript/lib"}, environment = "node"}

[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }
language-servers = ["vscode-html-language-server", "emmet-ls", "tailwindcss-ls"]

[[language]]
name = "css"
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "scss"
formatter = { command = 'npx', args = ["prettier", "--parser", "scss"] }

[[language]]
name = "javascript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true
language-servers = ["typescript-language-server", "emmet-ls", "tailwindcss-ls"]

[[language]]
name = "tsx"
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
auto-format = true
language-servers = ["typescript-language-server", "emmet-ls", "tailwindcss-ls"]

[[language]]
name = "json"
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "markdown"
formatter = { command = 'npx', args = ["prettier", "--parser", "markdown"] }
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true

[[language]]
name = "astro"
formatter = { command = 'npx', args = ["prettier", "--plugin", "prettier-plugin-astro", "--parser", "astro"] }
auto-format = true
language-servers = [ "astro-ls", "emmet-ls" ]
