local languages = {
	"astro",
	"c",
	"comment",
	"css",
	"csv",
	"diff",
	"dockerfile",
	"fish",
	"git_config",
	"gitcommit",
	"gitignore",
	"go",
	"graphql",
	"html",
	"javascript",
	"jq",
	"jsdoc",
	"json",
	"lua",
	"luadoc",
	"markdown",
	"markdown_inline",
	"query",
	"regex",
	"scss",
	"sql",
	"tsx",
	"typescript",
	"yaml",
}

return {
	{
		"nvim-treesitter/nvim-treesitter",
		branch = "main",
		build = ":TSUpdate",
	},
	{
		{
			"MeanderingProgrammer/treesitter-modules.nvim",
			dependencies = { "nvim-treesitter/nvim-treesitter" },
			opts = {
				ensure_installed = languages,
				fold = { enable = true },
				highlight = { enable = true },
				indent = { enable = true },
				incremental_selection = {
					enable = true,
					keymaps = {
						init_selection = "<A-o>",
						node_incremental = "<A-o>",
						scope_incremental = "<A-O>",
						node_decremental = "<A-i>",
					},
				},
			},
		},
	},
}
