gui:
  border: single
  sidePanelWidth: 0.3
  authorColors:
    "Pawel Grzybek": "yellow"
    "*": "default"
  theme:
    selectedLineBgColor:
      - black
os:
  editPreset: "nvim"
git:
  diffRenderers:
    - command: difft --syntax-highlight=off --context=6
      type: extDiff
