require("pawelgrzybek.autocmds")
require("pawelgrzybek.colorscheme")
require("pawelgrzybek.keymaps")
require("pawelgrzybek.options")
require("pawelgrzybek.user_commands")
require("pawelgrzybek.lazy")
