"ui.background" = { fg = "white"}
"ui.background.separator" = { fg = "white" }
"ui.cursor" = { bg = "gray" }
# "ui.cursor.normal" = {}
# "ui.cursor.insert" = {}
# "ui.cursor.select" = {}
"ui.cursor.match" = { bg = "gray" }
"ui.cursor.primary" = { modifiers = ["reversed"] }
# "ui.cursor.primary.normal" = {}
# "ui.cursor.primary.insert" = {}
# "ui.cursor.primary.select" = {}
# "ui.debug.breakpoint" = {}
# "ui.debug.active" = {}
# "ui.gutter" = {}
# "ui.gutter.selected" = {}
# "ui.highlight.frameline" = {}
"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { fg = "white",  modifiers = ["bold"] }
"ui.statusline" = { fg = "white" }
"ui.statusline.inactive" = { fg = "gray" }
# "ui.statusline.normal" = {}
# "ui.statusline.insert" = {}
# "ui.statusline.select" = {}
"ui.statusline.separator" = { fg = "gray" }
"ui.bufferline" = { fg = "gray" }
"ui.bufferline.active" = { fg = "white" }
# "ui.bufferline.background" = {}
# "ui.popup" = {}
# "ui.popup.info" = {}
"ui.window" = { fg = "gray" }
# "ui.help" = {}
# "ui.text" = {}
"ui.text.focus" = { bg = "gray" }
"ui.text.inactive" = { fg = "gray" }
# "ui.text.info" = {}
"ui.virtual.ruler" = { bg = "black" }
"ui.virtual.whitespace" = "gray"
"ui.virtual.indent-guide" = "gray"
"ui.virtual.inlay-hint" = { fg = "blue" , modifiers = ["italic", "underlined", "dim"], underline = { style = "line"} }
# "ui.virtual.inlay-hint.parameter" = { fg = "blue" , modifiers = ["italic", "underlined", "dim"], underline = { style = "line"} }
# "ui.virtual.inlay-hint.type" = { fg = "blue" , modifiers = ["italic", "underlined", "dim"], underline = { style = "line"} }
"ui.virtual.wrap" = "gray"
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold", "underlined"] }
"ui.menu" = {}
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.menu.scroll" = { fg = "white", bg = "#ff0000" }
"ui.selection" = { bg = "gray"}
# "ui.selection.primary" = { bg = "gray" }
"ui.highlight" = { bg = "gray" }
"ui.cursorline" = { bg = "black" }
"ui.cursorcolumn" = { bg = "black" }
"warning" = { fg = "yellow" }
"error" = { fg = "red" }
"info" = { fg = "blue" }
"hint" = { fg = "red" }
"diagnostic.hint" = { underline = { color = "red", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color ="red", style = "curl" } }
"diagnostic.unnecessary" = { underline = { color ="#ff0000", style = "curl" } }
"diagnostic.deprecated" = { underline = { color ="#ff0000", style = "curl" } }

"attribute" = "yellow"
"type" = "yellow"
"constructor" = "blue"
"constant" = "yellow"
"string"  = "green"
"comment" = { fg = "blue", modifiers = [ "dim", "italic" ]}
"variable" = "red"
"variable.other.member" = "green"
"label" = "magenta"
"keyword" = "magenta"
"function" = "blue"
"namespace" = "magenta"
"special" = { bg = "yellow", fg = "black" }
"markup.heading" = "blue"
"markup.list" = "red"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue", underline = { color = "blue", style = "line"} }
"markup.link.text" = "red"
"markup.quote" = "cyan"
"markup.raw" = "green"
"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "blue"
