"ui.background" = { fg = "white"}
"ui.background.separator" = { fg = "white" }
"ui.cursor" = { bg = "gray" }
# "ui.cursor.normal" = {}
# "ui.cursor.insert" = {}
# "ui.cursor.select" = {}
"ui.cursor.match" = { bg = "gray" }
"ui.cursor.primary" = { modifiers = ["reversed"] }
# "ui.cursor.primary.normal" = {}
# "ui.cursor.primary.insert" = {}
# "ui.cursor.primary.select" = {}
# "ui.debug.breakpoint" = {}
# "ui.debug.active" = {}
# "ui.gutter" = {}
# "ui.gutter.selected" = {}
# "ui.highlight.frameline" = {}
"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { fg = "white",  modifiers = ["bold"] }
"ui.statusline" = { fg = "white" }
"ui.statusline.inactive" = { fg = "gray" }
# "ui.statusline.normal" = {}
# "ui.statusline.insert" = {}
# "ui.statusline.select" = {}
"ui.statusline.separator" = { fg = "white", bg = "#ff0000" }
"ui.bufferline" = { fg = "gray" }
"ui.bufferline.active" = { fg = "white" }
# "ui.bufferline.background" = {}
# "ui.popup" = {}
# "ui.popup.info" = {}
"ui.window" = { fg = "gray" }
# "ui.help" = {}
# "ui.text" = {}
"ui.text.focus" = { bg = "gray" }
"ui.text.inactive" = { fg = "gray" }
# "ui.text.info" = {}
"ui.virtual.ruler" = { bg = "gray" }
"ui.virtual.whitespace" = "gray"
"ui.virtual.indent-guide" = "gray"
"ui.virtual.inlay-hint" = { fg = "gray" , modifiers = ["italic", "underlined"], underline = { style = "line"} }
# "ui.virtual.inlay-hint.parameter" = {}
# "ui.virtual.inlay-hint.type" = {}
"ui.virtual.wrap" = "gray"
"ui.virtual.jump-label" = { fg = "light-blue", modifiers = ["bold", "underlined"] }
"ui.menu" = {}
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.menu.scroll" = { fg = "white", bg = "#ff0000" }
"ui.selection" = { bg = "#37364A" } # this is only exception, for the color between the black and gray
"ui.selection.primary" = { bg = "gray" }
"ui.highlight" = { bg = "gray" }
"ui.cursorline" = { bg = "#2C2B3B" }
"ui.cursorcolumn" = { bg = "#2C2B3B" }
"warning" = { fg = "light-yellow" }
"error" = { fg = "light-red" }
"info" = { fg = "light-blue" }
"hint" = { fg = "#ABAABB" }
"diagnostic.hint" = { underline = { color = "#ABAABB", style = "curl" } }
"diagnostic.info" = { underline = { color = "light-blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "light-yellow", style = "curl" } }
"diagnostic.error" = { underline = { color ="light-red", style = "curl" } }
"diagnostic.unnecessary" = { underline = { color ="#ff0000", style = "curl" } }
"diagnostic.deprecated" = { underline = { color ="#ff0000", style = "curl" } }

"attribute" = "light-yellow"
"type" = "light-yellow"
"constructor" = "light-blue"
"constant" = "light-yellow"
"string"  = "light-green"
"comment" = { fg = "#ABAABB"}
"variable" = "light-red"
"variable.other.member" = "light-green"
"label" = "light-magenta"
"keyword" = "light-magenta"
"function" = "light-blue"
"namespace" = "light-magenta"
"special" = "light-yellow"
"markup.heading" = "light-blue"
"markup.list" = "light-red"
"markup.bold" = { fg = "light-yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "light-magenta", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "light-yellow", underline = { color = "light-yellow", style = "line"} }
"markup.link.text" = "light-red"
"markup.quote" = "light-cyan"
"markup.raw" = "light-green"
"diff.plus" = "light-green"
"diff.minus" = "light-red"
"diff.delta" = "light-blue"
