inherits = "base16_transparent"

"ui.popup" = { bg = "#272734" }
"ui.menu" = { bg = "#272734" }
"ui.virtual.ruler" = { bg = "#272734" }
"ui.linenr" = { modifiers=[ "dim" ] }
"ui.cursor" = { modifiers = ["reversed", "dim"] }
