[tui]
  vim_mode_default = true
screen_reader_detection_done = true

[tui.model_availability_nux]
gpt-6-astra = 4

[projects."/Users/pawelgrzybek/.dotfiles"]
trust_level = "trusted"

[projects."/Users/pawelgrzybek/Developer/nn1.dev/website"]
trust_level = "trusted"

[projects."/Users/pawelgrzybek/Developer/url.space/website"]
trust_level = "trusted"

[projects."/Users/pawelgrzybek/Developer/url.space/api"]
trust_level = "trusted"

[projects."/Users/pawelgrzybek/Developer/url.space"]
trust_level = "trusted"

[projects."/Users/pawelgrzybek/Developer/nn1.dev/api"]
trust_level = "trusted"
