[tui]
  vim_mode_default = true

[projects."/Users/pawelgrzybek/.dotfiles"]
trust_level = "trusted"

[projects."/Users/pawelgrzybek/Developer/nn1.dev/website"]
trust_level = "trusted"

[projects."/Users/pawelgrzybek/Developer/url.space/website"]
trust_level = "trusted"

[projects."/Users/pawelgrzybek/Developer/url.space/api"]
trust_level = "trusted"
